@URL = {{BASE_URL}}/membership/users
@ID = cmfq6ogg40007vtv26kzye6ew

### List users
GET {{URL}}
?pageSize=5
&previousCursor=cmfq3sod2002cwev23uwrgr20

### Create user
POST {{URL}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "name": "John Doe",
  "email": "gaia.ctrlaltdel@gmail.com"
}

### Update user
PUT {{URL}}/{{ID}}
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}

### Activate user
PATCH {{URL}}/{{ID}}/activate

### Deactivate user
DELETE {{URL}}/{{ID}}/deactivate

