
@URL = {{BASE_URL}}/telemetry/parameters
@ID = gknjgalzinu2wmmzr8u1k3s7

#### create parameter
POST {{URL}}
Content-Type: application/json

{
  "name": "Temperature 123",
  "unitOfMeasure": "Celsius",
  "factor": 0.01,
  "offset": 0,
  "isActive": true
}

#### list parameters
GET {{URL}}
?pageSize=20
&status=all
&name=Temperature

#### update parameter
PUT {{URL}}/{{ID}}
Content-Type: application/json

{
  "name": "Temperature Updated",
  "unitOfMeasure": "Fahrenheit",
  "factor": 0.2,
  "offset": 32
}

#### deactivate parameter
DELETE {{URL}}/{{ID}}
Content-Type: application/json

#### activate parameter
PATCH {{URL}}/{{ID}}
Content-Type: application/json

