@URL = http://localhost:3333/telemetry/stations
@ID = cmfuzcg3c004wkipv2h3z5200

#### list stations
GET {{URL}}
?pageSize=20

#### create station
POST {{URL}}
Content-Type: application/json

{
  "name": "Estação Central",
  "uid": "EST001",
  "latitude": -23.5505,
  "longitude": -46.6333,
  "address": "Av. Paulista, 1000 - São Paulo, SP",
  "parameterIds": ["param1", "param2", "param3"]
}

#### update station
PUT {{URL}}/{{ID}}
Content-Type: application/json

{
  "name": "Estação Central Atualizada",
  "uid": "EST001_UPDATED",
  "latitude": -23.5505,
  "longitude": -46.6333,
  "address": "Av. Paulista, 1000 - São Paulo, SP",
  "parameters": ["param1", "param2", "param4"]
}

#### deactivate station
DELETE {{URL}}/{{ID}}
Content-Type: application/json

#### activate station
PATCH {{URL}}/{{ID}}
Content-Type: application/json

#### station details
GET {{URL}}/{{ID}}
Content-Type: application/json
