@URL = {{BASE_URL}}/telemetry/stations
@ID = cmg2unkjg037y0wv2hw285w11

### list stations
GET {{URL}}
?pageSize=100

### create station
POST {{URL}}
Content-Type: application/json

{
  "station": {
    "name": "Estação Central",
    "uid": "EST001",
    "latitude": -23.5505,
    "longitude": -46.6333,
    "address": "Av. Paulista, 1000 - São Paulo, SP",
  },
  "parameterIds": ["param1", "param2", "param3"]
}

### update station
PUT {{URL}}/{{ID}}
Content-Type: application/json

{
  "station": {
    "name": "Estação Central Atualizada",
    "uid": "EST001_UPDATED",
    "latitude": -23.5505,
    "longitude": -46.6333,
    "address": "Av. Paulista, 1000 - São Paulo, SP",
  },
  "parameterIds": ["param1", "param2", "param4"]
}

### deactivate station
DELETE {{URL}}/{{ID}}
Content-Type: application/json

### activate station
PATCH {{URL}}/{{ID}}
Content-Type: application/json

### station details
GET {{URL}}/{{ID}}
Content-Type: application/json

### station parameters
GET {{URL}}/parameters/{{ID}}
Content-Type: application/json

### list stations by coords
GET {{URL}}/box/coords?lat1=&long1=&lat2=&long2=
Content-Type: application/json