name: 'Valid Workflow Job'

on:
  pull_request:
    branches:
      - main
      - production

jobs:
  enforce_main_to_production:
    name: 'Validate Main -> Production Merge'
    runs-on: ubuntu-latest
    if: github.base_ref == 'production'
    steps:
      - name: 'Check that source branch is main'
        if: github.head_ref != 'main'
        run: |
          echo "❌ ERROR: Pull requests to 'production' can only be made from the 'main' branch."
          echo "This PR is from the '${{ github.head_ref }}' branch, which is not allowed."
          exit 1
      - name: 'Approve merge from main'
        if: github.head_ref == 'main'
        run: echo "\o/ tudo correto,pode prosseguir!"


  block_production_to_main:
    name: 'Block Production -> Main Merge'
    runs-on: ubuntu-latest
    if: github.base_ref == 'main'
    steps:
      - name: 'Check that source branch is NOT production'
        if: github.head_ref == 'production'
        run: |
          echo "❌ ERROR: The 'production' branch cannot be merged back into 'main'."
          echo "Hotfixes should be done in a separate branch and merged to both 'main' and 'production'."
          exit 1
      - name: 'Approve merge into main'
        if: github.head_ref != 'production'
        run: echo "\o/ tudo correto,pode prosseguir!"
